version: "3.7"
services:
  server:
    container_name: node-server
    build:
      context: ./
      dockerfile: Dockerfile.server
    image: kuanluntseng/apihub:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      #      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    #      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - rabbitmq
      - redis

  mongodb:
    container_name: mongo-server
    image: mongo:latest
    restart: always
    volumes:
      #     [buggy line of code]
      #      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
  #    ports:
  #    - 27017:27017

  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3-management
    restart: always
    ports:
      #   [We only need to expose management web page to outside]
      #    - 5672:5672
      - 15672:15672

  worker:
    container_name: resizing-image-worker
    image: kuanluntseng/resizing-image-worker:latest
    build:
      context: ./
      dockerfile: Dockerfile.worker
    restart: always
    # volumes:
    #   - ./:/usr/src/app
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  redis:
    container_name: redis-server
    image: redis:latest
    restart: always

volumes:
  mongo-data:
