# Specify a base image
FROM node:latest


WORKDIR /usr/src/app

# Install some dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

ENV PORT=8000
EXPOSE ${PORT}

# Default command
CMD [ "npm", "start" ]
